#!/usr/bin/env bash
# Configures NGINX
sudo apt-get update -y
sudo apt-get install nginx -y
echo "Holberton School" > /var/www/html/index.nginx-debian.html
new_string="server_name _;\n\trewrite ^\/redirect_me google.com permanent;"
sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-enabled/default
service nginx start
