#!/usr/bin/env bash
# Installs HAproxy and configures it
apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.0
apt-get update -y
apt-get install -y haproxy=2.0.\*

CONF="\
frontend main
	bind *:80
	mode http
	option http-keep-alive
	default_backend web-server

backend web-server
	balance roundrobin
	server 1206-web-01 34.73.70.32:80 check
	server 1206-web-02 3.85.244.69:80 check
"

echo "$CONF" >> /etc/haproxy/haproxy.cfg
echo "ENABLED=1" >> /etc/default/haproxy
service haproxy start
