#!/usr/bin/env bash
# Process and PID file
echo $$ > /var/run/holbertonscript.pid
trap sigterm 15
sigterm()
{
    echo "I hate the kill command"
    rm -rf /var/run/holbertonscript.pid
    exit 0
}
trap sigint 2
sigint()
{
    echo "Y U no love me?!"
}
trap sigquit 3
sigquit()
{
    rm -rf /var/run/holbertonscript.pid
    exit 0
}
while ((1))
do
    echo "To infinity and beyond"
    sleep 2
done
