#!/usr/bin/env bash

fname="holbertonschool"
if [ -e $fname ]
then
    echo "holbertonschool file exists"
    if ! [[ -s $fname ]]
    then
       echo "holbertonschool file is empty"
    else
       echo "holbertonschool file is not empty"
    fi
    if [ -f $fname ]
    then
       echo "holbertonschool is a regular file"
    fi
else
    echo "holbertonschool file does not exists"
fi
