#!/usr/bin/env bash
# Web Debug 2 Advanced
sudo sed -i "s/80/8080/" /etc/nginx/sites-available/default
sudo chmod 204 /etc/nginx/nginx.conf
sudo sed -i '1iuser nginx;' /etc/nginx/nginx.conf
sudo pkill -f apache2
sudo -u nginx service nginx start
