#!/usr/bin/env bash
# Web Debug 2 Advanced
chmod 777 /etc/nginx/nginx.conf
sed -i "s/80/8080/" /etc/nginx/sites-available/default
sed -i '1iuser nginx;' /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx start
